### ISSUE TITLE
个人纠正几个BUG（可能有错，欢迎纠正）

### ISSUE THREAD

**Issue by Huansheng1** [qianguyihao/Web#101]
1.原型链：找到原型都没找到的话，如果你找的是一个属性的话，则返回 undefined，如果你找的是一个方法，则报错。
2.CSS基础/03-CSS样式表和选择器.md：属性名和冒号之间最好不要有空格（经验）。**然而我觉得是应该要有冒号，伪类元素的冒号前 和 属性值与单元之间 才应该是不应该有冒号**
3.CSS基础/01-CSS属性：字体属性和文本属性.md：vertical-align: middle; /指定行内元素（inline）或表格单元格（table-cell）元素的垂直对齐方式。/--->vertical-align的描述错误，应该加：行内块元素，主要是用于图片与表格 与文本对齐
4.闭包问题.md好像空白啊
5.offset内容里所述：div.style.left = parseInt(div.style.left)+10+"px";  //NaN不能用--->经测试并没有报错，运行正常。应该修改为-->//如果 style="left: 0px" 属性不存在，返回为NaN，无法修改位置
……待续，后面的还没看。

**Comment by Y0QIN** [comment]
JavaScript基础/05-typeof和数据类型转换: 使用 parseInt()函数：字符串 -> 整数, 3如果字符串是一个空串或者是一个全是空格的字符串，转换时会报错。
经测试并没有报错，运行正常,返回NaN

**Comment by Huansheng1** [comment]
Vue后面都比较简略，希望能等到后续更新或者简单项目实战，在看的推荐直接看Vue官网文档

**Comment by qianguyihao** [comment]
@Huansheng1 感谢补充，已更正。
