### ISSUE TITLE
图片全部加载不出来

### ISSUE THREAD

**Issue by Xinze15** [qianguyihao/Web#106]

**Comment by qianguyihao** [comment]
生活所迫。图片url所在的域名，我很早就已经本案了。但是由于我忘了及时更新备案信息上的联系方式，导致前几天我的备案信息突然失效了。我已经重新申请域名备案了，等过几天就会有结果。

域名异常期间，你可以通过在线的形式看GitHub上的内容，GitHub网站的图片一直是可以正常打开的，因为GitHub网站的在线图片，是GitHub官网提供的图床服务。

感谢你的关注，这个项目会一直更新下去的。

**Comment by Xinze15** [comment]
谢谢,你的项目做的很好。

**Comment by qianguyihao** [comment]
@Xinze15 域名备案问题已经修复，现在可以正常展示图片了。
