### ISSUE TITLE
javascript开发积累

### ISSUE THREAD

**Issue by 1078559858** [qianguyihao/Web#113]
if ('str1' == ('str1' || 'str2')){
    console.log('smyhvae);
}
注意，上面的代码，根本就不会走 console.log语句，因为if里面的内容是false。

错误地方：
1. console.log中少一个单引号。
2. 这个if语句里面的内容是true，会走console的代码。

**Comment by qianguyihao** [comment]
@1078559858 感谢指正，已修复。
