### ISSUE TITLE
浏览器的介绍-勘误

### ISSUE THREAD

**Issue by deepforce** [qianguyihao/Web#117]
原因：段落重复了一段。
位置：[link](https://github.com/qianguyihao/Web/blob/master/01-HTML/02-%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E4%BB%8B%E7%BB%8D.md#2js-%E5%BC%95%E6%93%8E)

**Comment by qianguyihao** [comment]
@deepforce  感谢指正，已修复。
