### ISSUE TITLE
内容是不是太少了

### ISSUE THREAD

**Issue by sing-zzj** [qianguyihao/Web#145]
看这个还需要看视频吗？感觉内容有点少，希望能够增加一点练习。

**Comment by bx2651** [comment]
感觉js和css部分看完基本不用看视频了，vue或者react看完还是再找个视频看一下跟着写一下项目比较好。

**Comment by qianguyihao** [comment]
> 感觉js和css部分看完基本不用看视频了，vue或者react看完还是再找个视频看一下跟着写一下项目比较好。

正解。教程还在不断完善中，是一项浩瀚工程。
