### ISSUE TITLE
离线无法查看图片

### ISSUE THREAD

**Issue by kaikee-Snow** [qianguyihao/Web#146]
教程很好，最大的问题在于md链接图片都是需要联网的而不是本地的，导致离线状态下无法看到图片。如果能下载到本地就最好了。另外语言逻辑稍显混乱，排版格式也需要改进。

**Comment by qianguyihao** [comment]
> 教程很好，最大的问题在于md链接图片都是需要联网的而不是本地的，导致离线状态下无法看到图片。如果能下载到本地就最好了。另外语言逻辑稍显混乱，排版格式也需要改进。

1、图片目前采用的都是在线图床的方式，这是标准的 markdown 写法。你可以用第三方工具把 md 文件导出为pdf文件，就可以离线看图片了。

2、语言逻辑和排版的问题，如果你觉得有改进之处，可以提交 issues 或者 pr。
