### ISSUE TITLE
浏览器那篇文章中的链接失效

### ISSUE THREAD

**Issue by Terencesun** [qianguyihao/Web#153]
地址：https://github.com/qianguyihao/Web/blob/master/01-HTML/02-%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E4%BB%8B%E7%BB%8D.md

失效链接：https://www.2cto.com/kf/201202/118111.html

**Comment by qianguyihao** [comment]
@Terencesun 已修复，感谢指正。
