### ISSUE TITLE
这块儿有问题

### ISSUE THREAD

**Issue by zoyo94** [qianguyihao/Web#166]
浏览器根据回调函数的返回值来决定元素的排序：（重要）

-   如果返回一个大于 0 的值，则元素会交换位置

-   **如果返回一个小于 0 的值，则元素位置不变**

-   如果返回一个等于 0 的值，则认为两个元素相等，则不交换位置

大于0，不交换吧 小于0才交换。看了半天做实验手动模拟了下 怎么都不对。我晕了

**Comment by qianguyihao** [comment]
我写的没错。是你理解错了。
