### ISSUE TITLE
建议使用 docsify 部署一个 page 服务

### ISSUE THREAD

**Issue by lesonky** [qianguyihao/Web#168]
啥也不用加,就直接 init 一个 docsify 文件, 启动一下 page ,就直接能看了,主要是方便查看,如果有域名可以托管到 cloudflare 上,这样通过cdn,可以解决图片看不到的问题

**Comment by qianguyihao** [comment]
谢谢建议。这个项目，我现在每月需要支付30元左右的图床费用，压力略大。我准备逐渐把项目内容同步到语雀上，对于读者而言，可以避免网络不稳定的问题；对于我而言，既可以减轻图床压力，也方便维护。我最大的想法是：把更多的精力放在内容创作本身，不要做太多技术维护的事情。
