### ISSUE TITLE
作者好，想请教学完了html+css后的切图问题

### ISSUE THREAD

**Issue by djc-Sherlock** [qianguyihao/Web#170]
作者你好，我跟着你的教程学完了html+css,可是自己仿照别的站点切图还是切不出来。我自己很迷茫，感觉到了沮丧，但是我前端同事说，现在都是拿人家组件直接使用，很少这样切图了，可以暂时跳过，能给我一点建议嘛

**Comment by qianguyihao** [comment]
切图一般指的是从设计软件里导出图片。你想表达的意思应该是：仿照市面上的网站做个demo，是否有必要？对于初学者来说，当然是有必要的。你也可以把自己的独特想法实现出来，做做一些小项目，放到github上。都是一种历练

**Comment by jialiangzai** [comment]
试试自己切吧，就是没插件块
