### ISSUE TITLE
关于例子结果不一致的地方

### ISSUE THREAD

**Issue by Machars** [qianguyihao/Web#171]
在学习的过程中,我验证了<<06-JavaScript基础：ES6语法/06-ES6：箭头函数.md>>中的两个例子,发现结果不一致:
const obj = { name: '千古壹号' };

function fn1() {
    console.log(this); // 第一个 this
    return () => {
        console.log(this); // 第二个 this
    };
}

const fn2 = fn1.call(obj);
fn2();

这个输出的结果是:
{ name: '千古壹号' }
{ name: '千古壹号' }
_____________________________________________________________
const name = '许嵩';
const obj = {
    name: '千古壹号',
    sayHello: () => {
        console.log(this.name);
    },
};

obj.sayHello();

这个输出结果是: 空的字符串

**Comment by qianguyihao** [comment]
第一个地方，我写的没错，是你理解错了。打印结果是对象obj，不是字符串，JSON.stringify(obj)的打印结果才是字符串。可以用  typeof 判断一下数据类型便知。你在浏览器里看到的结果，是浏览器控制台帮你做的二次处理而已，不是真实的打印结果。

第二个地方，是我写错了，应该把 const 改成 var 就行了。已修复。谢谢指正。

**Comment by Machars** [comment]
谢谢您上次的回答
在练习也正中又发现了一个问题

05-02.面向对象：类的定义和继承的几种方式.md,方式二中的原型链实现继承,缺点是如果修改children1实例的name属性,children2实例中的name属性也会跟着改变, 我写了如下的代码验证

function Dog(){
  this.name='dog'
}

function Taididog(){
  this.type='taidi'
}
Taididog.prototype=new Dog()

let taididog1 = new Taididog()
let taididog2 = new Taididog()
taididog1.name = 'taididog1'
console.log(taididog2.name) //输出的是  dog
console.log(taididog1.name) //输出的是 taididog1

改变了children1的name属性值,并没有引起children2.name属性值的变化, 是不是我理解有误





发送自 Windows 10 版邮件应用

发件人: 千古壹号
发送时间: 2021年5月23日 23:14
收件人: qianguyihao/Web
抄送: Machars; Author
主题: Re: [qianguyihao/Web] 关于例子结果不一致的地方 (#171)

第一个地方，我写的没错，是你理解错了。打印结果是对象obj，不是字符串，JSON.stringify(obj)的打印结果才是字符串。可以用 typeof 判断一下数据类型便知。你在浏览器里看到的结果，是浏览器控制台帮你做的二次处理而已，不是真实的打印结果。
第二个地方，是我写错了，应该把 const 改成 var 就行了。已修复。谢谢指正。

**Comment by qianguyihao** [comment]
@Machars  感谢指正，已修复。准确来说是：要改变children1的obj（引用数据类型），才会引起  children2.obj的变化~
