### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by OoadaioO** [qianguyihao/Web#175]
https://github.com/qianguyihao/Web/blob/master/02-CSS%E5%9F%BA%E7%A1%80/15-Sass%E5%85%A5%E9%97%A8.md

“”“ 
大家都知道，js 中可以自定义【发量】...
“”“
应该是【变量】吧，内容中有很多【发量】

**Comment by qianguyihao** [comment]
已修复。感谢指正 @OoadaioO
