### ISSUE TITLE
整个项目下面的这些图片资源无法加载和下载，能不能直接将图片保存在项目里面。

### ISSUE THREAD

**Issue by Yossarian161** [qianguyihao/Web#19]
http://7sby7r.com1.z0.glb.clouddn.com/2015-10-03-css-28.png
http://img.smyhvae.com/20180201_2330.png
http://img.smyhvae.com/20180311_1100.png
http://img.smyhvae.com/20180311_1117.png
http://img.smyhvae.com/20180220_1338.png
http://img.smyhvae.com/20180223_2213.gif
http://img.smyhvae.com/20180224_2110.gif
http://img.smyhvae.com/20180310_1040.png
http://7sby7r.com1.z0.glb.clouddn.com/2015-10-03-css-27.jpg
http://7sby7r.com1.z0.glb.clouddn.com/2015-10-03-css-30.jpg
http://img.smyhvae.com/20180506_2240.png
http://img.smyhvae.com/20180506_2320.png
http://img.smyhvae.com/20180506_2330.png
http://img.smyhvae.com/20180509_1058.png
http://img.smyhvae.com/20180509_1500.png
http://img.smyhvae.com/20180509_1505.png
http://img.smyhvae.com/20180522_1240.png
http://img.smyhvae.com/20180610_2130.png

**Comment by smyhvae** [comment]
@Yossarian161   谢谢你的反馈。我已经将以上有问题的图片，全部修复。再次谢谢。

图片目前采用的是外链，而非保存在项目中。如果保存在项目的文件夹下，会存在两个问题：

- 项目过大。

- 直接拷贝单篇markdown文档放在其他地方阅读，图片无法打开。
