### ISSUE TITLE
 04-JavaScript基础 / 28-浅拷贝和深拷贝.md  错误

### ISSUE THREAD

**Issue by chaihongjun** [qianguyihao/Web#202]
> 注意，例 4 在实际开发中，会经常遇到，一定要掌握。它的作用是：将 obj1 的值追加到 obj2 中。如果两个对象里的属性名相同，则 obj12 中的值会被 obj2 中的值覆盖。

这里的 **如果两个对象里的属性名相同，则 obj12 中的值会被 obj2 中的值覆盖。**  应该是 如果两个对象里的属性名相同，则 obj2 中的值会被 obj1 中的值覆盖。

**Comment by qianguyihao** [comment]
@chaihongjun 已修复，感谢指正。
