### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by gNaW-tuanortsA** [qianguyihao/Web#21]
Web/03-JavaScript进阶/06-作用域和闭包--->内存泄漏内存溢出--->情况3举例

var arr = new Array[100000]; 

请更改笔误，谢谢！

**Comment by gNaW-tuanortsA** [comment]
不是，情况3中你是（var arr = new Array[100000];） 这样写的

**Comment by qianguyihao** [comment]
> 不是，情况3中你是（var arr = new Array[100000];） 这样写的

已修复。谢谢您的指正，非常感谢。
