### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by JiaoYang1024** [qianguyihao/Web#22]
css01里的这个图片
https://camo.githubusercontent.com/eedba3fdcf4a77513183078909dfdbdca8362c81/687474703a2f2f696d672e736d79687661652e636f6d2f323031352d31302d30332d6373732d31382e706e67

**Comment by qianguyihao** [comment]
> css01里的这个图片
> https://camo.githubusercontent.com/eedba3fdcf4a77513183078909dfdbdca8362c81/687474703a2f2f696d672e736d79687661652e636f6d2f323031352d31302d30332d6373732d31382e706e67

你好，这张图片我这里可以正常显示。你清除[浏览器缓存](https://github.com/qianguyihao/Web/issues/20#issue-390074432)试一下。
