### ISSUE TITLE
vue中部分bug

### ISSUE THREAD

**Issue by AlexSeven77** [qianguyihao/Web#223]
12-vue基础里 02中 537行， console.log(_this.msg)错误，应该为this

**Comment by shuaixiangzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qianguyihao** [comment]
@AlexSeven77  我写的没错，因为前面写了`var _this = this;`
