### ISSUE TITLE
JS-28-对象的创建&构造函数 的一个小笔误

### ISSUE THREAD

**Issue by zhiruozzy** [qianguyihao/Web#226]
位置：
在“创建自定义对象的几种方法”中，方法二：工厂模式

内容：
第一次看到这种工厂模式时，你可能会觉得陌生。如果简化一下，可以写成下面这种形式，更容易理解：（也就是，利用 new Object 创建对象）

var obj = new Obect();
obj.name = '猪八戒';
obj.age = 28;
obj.gender = '男';
obj.sayHi = function () {
    alert('hello world');
};

代码的第一行应该是 var obj = new Object(); 
少了一个字母，小笔误

**Comment by qianguyihao** [comment]
@zhiruozzy 感谢指正，已修复。
