### ISSUE TITLE
06-Promise的链式调用中resolve参数问题

### ISSUE THREAD

**Issue by Sina0709** [qianguyihao/Web#235]
`new Promise((resolve, reject) => {
    ajax('a.json', (res) => {
        console.log(res);
        resolve();//其中resolve(),应该改为resolve(res)？要不然then的res为undefined
    });
})
    .then((res) => {
        console.log('a成功');
        return new Promise((resolve, reject) => {
            ajax('b.json', (res) => {
                console.log(res);
                resolve();
            });
        });
    })`
这只是我的一点疑问，如果错误，希望楼主批评指正，谢谢！最后，博客很赞！

**Comment by qianguyihao** [comment]
@Sina0709 感谢指正，你理解得对。近期我对 Promise 相关的主题，做了大量更新。欢迎阅读并提出宝贵建议。
