### ISSUE TITLE
作用域那节的疑问

### ISSUE THREAD

**Issue by inkn** [qianguyihao/Web#24]
Q：每调用一次函数就会创建一个新的函数作用域  ？

函数作用域不是在创建函数时就确定了吗？在函数执行阶段创建的时函数上下文环境。

**Comment by qianguyihao** [comment]
> 每调用一次函数就

谢谢指正，已修复。非常感谢~

**Comment by qianguyihao** [comment]
> Q：每调用一次函数就会创建一个新的函数作用域 ？

> 函数作用域不是在创建函数时就确定了吗？在函数执行阶段创建的时函数上下文环境。

谢谢指正，已修复。非常感谢~
