### ISSUE TITLE
文字表述错误

### ISSUE THREAD

**Issue by Coder-ZJ** [qianguyihao/Web#244]
1、gcc、clang 是编译工具，而不是什么编辑工具；
2、ESLint、TSLint 是语法规则和代码风格的检查工具，而不是什么编译工具。
位置：VS Code的使用 -> VS Code 的安装
<img width="896" alt="image" src="https://user-images.githubusercontent.com/16216892/174698081-6dd8043e-156f-4b36-baec-a72a2356c657.png">

**Comment by qianguyihao** [comment]
@Coder-ZJ 感谢指正，已修复。

**Comment by Coder-ZJ** [comment]
张进已收到您的邮件，会尽快给予回复
