### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by suika3046** [qianguyihao/Web#245]
[04-JavaScript基础]/09-数据类型转换.md
![截屏2022-06-21 11 09 05](https://user-images.githubusercontent.com/64206623/174708461-f40d1c04-8a55-47ad-b898-0bad0ef102e6.jpg)

**Comment by 271374667** [comment]
更多错误
**JavaScript基础/27-对象的创建&构造函数**
```js
var obj = new Obect();
obj.name = '猪八戒';
obj.age = 28;
obj.gender = '男';
obj.sayHi = function () {
    alert('hello world');
};
```
第一行，我猜作者是想写
```js
var obj = new Object();
```

**Comment by qianguyihao** [comment]
@suika3046 @271374667 感谢指正，已修复。
