### ISSUE TITLE
“初识HTML”部分出现一个错别字

### ISSUE THREAD

**Issue by fcjz** [qianguyihao/Web#255]
初识HTML部分，html骨架标签分类，<html></html>的说明，“成为”应改为“称为”。

======================================

刚开始进入社区为开源做贡献，有没做对的地方请指正。

其他问题我看issue中提的差不多了，和他们比起来，这个错误似乎显得微不足道，但我还是觉得应该提出，所以发起了issue。

**Comment by rackey1993** [comment]
同样留意到了这个错别字 ￣□￣｜｜

**Comment by qianguyihao** [comment]
@rackey1993 @fcjz  感谢指正，已修复。
