### ISSUE TITLE
关于JS进阶中this一篇想请教一个问题

### ISSUE THREAD

**Issue by junglehunter96** [qianguyihao/Web#26]
![image](https://user-images.githubusercontent.com/48642399/54824344-a0c50900-4ce5-11e9-9f12-279d6e15f85f.png)
我想请教一下这里的console.log(i)为什么打印结果总是5呢
您原文给出的解释是：“代码执行完毕后，i已经等于5了。因为一旦运行程序，for循环已经执行完了，此时i等于5。”事件源不该是我点击那个div吗 为什么呢个人理解还是不够，或者是前面的基础还不够牢固，想请大哥指点

**Comment by mmonke** [comment]
建议你去网上搜一下闭包，有关于这个的详细讲解

**Comment by mmonke** [comment]
看一下这个网站吧https://www.cnblogs.com/qieguo/p/5457040.html

**Comment by junglehunter96** [comment]
谢谢哥 这位博主老哥写的很清楚了
