### ISSUE TITLE
关于博客的一点建议

### ISSUE THREAD

**Issue by sunweiguo** [qianguyihao/Web#33]
建议还是用github page来呈现，或者第三方平台，这个有的时候图片啥的都是问题，体验不是太好。因为毕竟3.3k的人star了嘛，提升一下阅读体验对于这三千多人也是福利，最后谢谢您的贡献。

**Comment by qianguyihao** [comment]
@sunweiguo 目前来看，大部分图片都能正常显示。

少数图片尺寸过大，导致显示异常，这个问题主要是因为 github 是国外的网站，访问起来比较慢。

如果有无法显示的图片，可以提交issues，具体指出是哪一张图片，我把尺寸压缩一些，就ok了。

从维护成本的角度来看，暂时不打算把把内容同步到其他平台。

当然，你也可以直接 clone 项目到本地，在本地预览 markdown文件，效果更佳。

**Comment by sunweiguo** [comment]
> @sunweiguo 目前来看，大部分图片都能正常显示。
> 
> 少数图片尺寸过大，导致显示异常，这个问题主要是因为 github 是国外的网站，访问起来比较慢。
> 
> 如果有无法显示的图片，可以提交issues，具体指出是哪一张图片，我把尺寸压缩一些，就ok了。
> 
> 从维护成本的角度来看，暂时不打算把把内容同步到其他平台。
> 
> 当然，你也可以直接 clone 项目到本地，在本地预览 markdown文件，效果更佳。

好吧。。。
