### ISSUE TITLE
关于CSS中选择器的问题

### ISSUE THREAD

**Issue by dolphintt** [qianguyihao/Web#42]
您好，在“02-CSS/03-CSS样式表和选择器”这部分中提到了交集选择器，您说用.隔开，这里有误。应该是两个选择器之间没有空格分隔，如果后一个选择器是类选择器，则写为div.special，如果是id选择器，则写为div#special.
谢谢您创造并维护这个项目~

**Comment by qianguyihao** [comment]
@dolphintt 感谢指正，已修复。
