### ISSUE TITLE
请教：为什么js是单线程，却可以异步请求？

### ISSUE THREAD

**Issue by XiFanYin** [qianguyihao/Web#45]
我是一个正在学习前端的android开发人员，如题所说，为什么js是单线程，却可以异步请求？单线程和异步明明就是两个相违背的概念~

**Comment by wangzw** [comment]
> 单线程和异步明明就是两个相违背的概念

这个说法是不对的。举个例子，你把给泡面倒上开水放在一边，然后就去看电视了，10分钟面好了可以吃了。你是单线程的，但是不妨碍泡面异步进行。

**Comment by Div12span** [comment]
单线程编译错了不执行。编译没问题，执行到某一行错了，就不再往下执行。并且编译完了读一行执行一行。里面知识点可不少，比如函数就是值执行前一刻才编译。

**Comment by XiFanYin** [comment]
> > 单线程和异步明明就是两个相违背的概念
> 
> 这个说法是不对的。举个例子，你把给泡面倒上开水放在一边，然后就去看电视了，10分钟面好了可以吃了。你是单线程的，但是不妨碍泡面异步进行。

我觉得你说的这个叫并发比较合适吧，并发实现方式：多线程或多进程

**Comment by XiFanYin** [comment]
> 单线程编译错了不执行。编译没问题，执行到某一行错了，就不再往下执行。并且编译完了读一行执行一行。里面知识点可不少，比如函数就是值执行前一刻才编译。

边编译边执行和单线程异步有什么关系呢？

**Comment by Div12span** [comment]
和单线程有点关系吧。和异步属实没啥关系。不过定时器是开异步执行的。我也是半吊子正在学

**Comment by gdchent** [comment]
...，我解释一下吧，不对勿喷，个人理解：js是单线程， 当我们开启一个ajax请求的时候，会压入队列里面由http线程执行，此时js引擎线程（也就是我们的主线程，对应安卓的主线程）同步往下执行，当http线程响应后，通知ui线程执行回调方法更新ui，跟安卓中的主线程跟子线程其实差不多，安卓中子线程请求网络，请求完成后通知主线程然后handler发送通知更新ui线程。道理差不多

**Comment by wangzw** [comment]
> > > 单线程和异步明明就是两个相违背的概念
> > 
> > 
> > 这个说法是不对的。举个例子，你把给泡面倒上开水放在一边，然后就去看电视了，10分钟面好了可以吃了。你是单线程的，但是不妨碍泡面异步进行。
> 
> 我觉得你说的这个叫并发比较合适吧，并发实现方式：多线程或多进程

是并发，也是异步。所谓异步，你发起一件事情，不等它结束就返回了，过一会儿再去查看事情处理的结果，或者处理完成的时候进行回调通知。

> 并发实现方式：多线程或多进程

单进程单线程也可以“并发”，比如以前的CPU都是单核单物理线程，仍然可以并发多任务。

**Comment by XiFanYin** [comment]
@gdchent 既然有http线程，又有主线程，那么意味着js代码执行的过程中最少有两个线程在运行，既然有两个线程，怎么会叫单线程呢？

**Comment by gdchent** [comment]
不是，js是单线程，js代码是由js引擎在js引擎线程执行，是同步的，遇到异步就加入队列，浏览器是多线程。你看书或者网上搜

**Comment by gdchent** [comment]
@XiFanYin 自己先到网上搜下再提问，已经解释的很详细了  浏览器是多线程，js是单线程

**Comment by XiFanYin** [comment]
@gdchent 你说的好像有点理解了，把js放到浏览器引擎环境下，视乎能解释的通了，js是单线程，引擎不是单线程。另外两个小问题看能能再赐教一下： 第一个问题：一段代码是否需要加入队列变成异步，是浏览器默认指定的规则吗？规则需要开发人员了解和记忆吗？第二个问题：比如有这样的需求让联网请求变成同步执行，让一部分同步代码变成异步，有没有办法做到？

**Comment by gdchent** [comment]
@XiFanYin https://segmentfault.com/a/1190000012925872  看这个

**Comment by XiFanYin** [comment]
@gdchent 这个文章推荐的太好了，谢谢你帮我解惑
