### ISSUE TITLE
图片加载需要联网，但我大部分时间所处环境是不允许联网的

### ISSUE THREAD

**Issue by 1042970366** [qianguyihao/Web#48]
您好，将您的笔记文件下载下来之后打开发现图片加载不出来，看了下图url是需要联网才能加载出来的，但我的大部分时间所处环境是不允许联网的，所以可不可以麻烦下大佬将您的源笔记文件给我发一下~或者告诉下我其他的解决方法~

**Comment by qianguyihao** [comment]
学前端的第一步：先连网。

**Comment by Div12span** [comment]
说实话。这是我学前端依赖觉得最轻松简单的一步了...  以后的很多步要让我炸了.....

**Comment by 1042970366** [comment]
好吧,还是谢谢啦~


------------------ 原始邮件 ------------------
发件人: "Div12span"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 晚上9:27
收件人: "qianguyihao/Web"<Web@noreply.github.com>;
抄送: "飞云"<1042970366@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [qianguyihao/Web] 图片加载需要联网，但我大部分时间所处环境是不允许联网的 (#48)




说实话。这是我学前端依赖觉得最轻松简单的一步了...  以后的很多步要让我炸了.....
