### ISSUE TITLE
图片里的内容不对

### ISSUE THREAD

**Issue by 97thjingba** [qianguyihao/Web#54]
Web/14-前端面试/02-CSS盒模型及BFC.md

![WeChatf95b6a5658d1c4ef621fac1ad298e585](https://user-images.githubusercontent.com/39749571/64602300-1be3be00-d3f1-11e9-80ab-7aae518549d6.png)

蓝色盒子应该是 margin-top

**Comment by qianguyihao** [comment]
@97thjingba 感谢指正，已修复。
