### ISSUE TITLE
span是块级元素吗？

### ISSUE THREAD

**Issue by daialihexiaoniu** [qianguyihao/Web#55]
![image](https://user-images.githubusercontent.com/15117153/64673966-2dd16980-d4a2-11e9-8597-cdf1e410ab3d.png)

我觉得这边形容span和div都是块级元素不严谨，span不是行内元素吗

**Comment by csjiabin** [comment]
span是行内标签根本不是块标签，老哥你前端没学好啊

**Comment by daialihexiaoniu** [comment]
对啊…他这边自己写github上是行内啊…我不是再问吗什么鬼啊





------------------ 原始邮件 ------------------
发件人: jaibin <notifications@github.com&gt;
发送时间: 2019年9月11日 22:06
收件人: qianguyihao/Web <Web@noreply.github.com&gt;
抄送: 阿狸 <397698632@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[qianguyihao/Web] span是块级元素吗？ (#55)

**Comment by daialihexiaoniu** [comment]
> span是行内标签根本不是块标签，老哥你前端没学好啊

我不是说了span是行内了吗，自己既没看清吧，人家GitHub 上面写的是块级的我在问他是不是写错了好么。凭什么一上来就指责我没学好前端

**Comment by PachVerb** [comment]
> > span是行内标签根本不是块标签，老哥你前端没学好啊
> 
> 我不是说了span是行内了吗，自己既没看清吧，人家GitHub 上面写的是块级的我在问他是不是写错了好么。凭什么一上来就指责我没学好前端
道友，你误解了他的话了。它的意思是说块级div 和 行内span ...... ，你看下面内容嘛。

**Comment by PachVerb** [comment]
他那里没问题的
