### ISSUE TITLE
额，楼主这些都感觉是很基础的东西啊

### ISSUE THREAD

**Issue by zzhun** [qianguyihao/Web#57]

**Comment by sabertazimi** [comment]
建议从 https://developer.mozilla.org/zh-CN/docs/Learn 这里开始入门。
这个仓库下有些东西非常旧，而且质量有些参差不齐，对于新手来说不适宜用作入门。
包括各种工具和框架 (如 React) 的使用，也建议看官方的入门教程，写得都非常详细、简单易懂。

仓库里一些小 tips 和面试题倒是有学习的价值。

**Comment by sabertazimi** [comment]
https://developer.mozilla.org/zh-CN/docs/Learn 新手入门快车道

**Comment by qianguyihao** [comment]
内容很基础没关系，想入门的前端小白有很多。而且这个项目会持续完善下去。

这个项目的主要作用有：

- 1、网上的大部分入门教程，都不太适合初学者，本项目争取照顾到每一位入门者的同理心。

- 2、帮助入门web前端的人提供一个精品学习资源，提高学习效率，少走很多弯路。

- 3、可以当做是前端字典，随时翻阅，查漏补缺。
