### ISSUE TITLE
错误指正

### ISSUE THREAD

**Issue by ybbbzZ** [qianguyihao/Web#59]
03-javascript基础中的32节-事件委托中的最后一串代码：
` // 获取父节点，并为它注册click事件。 false 表示事件在冒泡阶段触发（默认）
    document.getElementById("parent-list").addEventListener("click", function (e) {
        // event.target 代表的是子元素。toUpperCase 指的是转换为大写字母
        if (e.target && e.target.nodeName.toUpperCase == "LI") {
            // 真正的处理过程在这里
            console.log("List item ", e.target.id, " was clicked!");
        }
    }, false);`
中的toUpperCase后应加括号，否则js事件绑定失败

**Comment by qianguyihao** [comment]
@ybbbzZ 感谢指正，已修复。国庆节快乐~
