### ISSUE TITLE
vscode快捷键

### ISSUE THREAD

**Issue by rebeccacaca** [qianguyihao/Web#84]
您好，win 下Fn + ← 将光标定位到当前行的最左侧，不可用
但是ctrl + ← 可以将光标移动到单词的开头

**Comment by soloistgui** [comment]
哥，感谢提醒，我试了，win 下Fn + ← 将光标定位到当前行的最左侧，外接键盘可以，笔记本键盘不行。我再研究研究 😃&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"REBECCACACACA"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 下午2:50
收件人:&nbsp;"qianguyihao/Web"<Web@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianguyihao/Web] vscode快捷键 (#84)




您好，win 下Fn + ← 将光标定位到当前行的最左侧，不可用
 但是ctrl + ← 可以将光标移动到单词的开头
