### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by zhang1pr** [qianguyihao/Web#9]
Web/02-CSS/04-CSS选择器：伪类，第一个动图不动且显示不全。
Web/02-CSS/05-CSS样式表的继承性和层叠性， 第一张图片显示不全。
Web/02-CSS/06-CSS盒模型详解，倒数第三张图片显示不全。
Web/02-CSS/06-CSS盒模型详解，IE盒子模型图中的comment，padding误写为pading。
Web/02-CSS/07-浮动，方法3：隔墙法的第一张图片，内墙法的第二张图片与最后一张图显示不全。

Web/03-JavaScript基础/10-DOM操作，插入节点的最后一行{20180129_2125.png}，疑似图片未加载。

**Comment by zhang1pr** [comment]
Web/02-CSS/06-CSS盒模型详解，这一节中IE盒子模型图中的comment，padding误写为pading

**Comment by zhang1pr** [comment]
Web/02-CSS/06-CSS盒模型详解, 倒数第三张图显示不全。

**Comment by zhang1pr** [comment]
另外我有pull request纠正一些拼写错误，可以看一下。

**Comment by smyhvae** [comment]
好，正在看，非常感谢你~

**Comment by smyhvae** [comment]
gif图没有动 or 显示不全，是因为网络不好，可以多刷新几次，图片本身并没有问题。也可以把整个项目下载下来，在本地查看md格式的文档。

另外，`20180129_2125.png`图片问题已经修复。

最后，非常感谢你～

**Comment by zhang1pr** [comment]
Web/04-前端基本功：JavaScript特效/02-scroll家族和缓动动画.md，所有图片以及rar文件无法显示。

**Comment by mogiihu** [comment]
10-ES6中后几篇图片都显示不出来，只显示了个图片名。下载下来打开也没用。

**Comment by smyhvae** [comment]
@mogiihu  已修改，谢谢~

**Comment by Caibiy** [comment]
08-04下 jQuery 中的 JSONP 代码放反了

**Comment by smyhvae** [comment]
@Caibiy 具体是哪个位置的代码放反了？
