### ISSUE TITLE
描述错误

### ISSUE THREAD

**Issue by 1078559858** [qianguyihao/Web#95]
/02-CSS基础/01-CSS属性：字体属性和文本属性.md
vertical-align: middle; /*指定行内元素（inline）或表格单元格（table-cell）元素的垂直对齐方式。*/

vertical-align的描述错误，应该是：行级元素，inline-block也可以。而不是行内元素。

**Comment by qianguyihao** [comment]
@1078559858 感谢指正，已修复。
